apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipai-backend
  namespace: ipai
  labels:
    app: ipai-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ipai-backend
  template:
    metadata:
      labels:
        app: ipai-backend
    spec:
      containers:
      - name: backend
        image: ipai/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ipai-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: ipai-secrets
              key: redis-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ipai-secrets
              key: secret-key
        - name: ENVIRONMENT
          value: "production"
        - name: OLLAMA_HOST
          value: "http://ollama-service:11434"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ipai-backend-service
  namespace: ipai
spec:
  selector:
    app: ipai-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP